server:
  port: 8081
  #tomcat: 
    #compression: on
spring:
  kafka:
    consumer:
      group-id: foo
      auto-offset-reset: earliest
  application:
    name: service-springbootForMybatis
  datasource: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: cxh
    password: 123